on: push
name: Test Workflow
jobs:
  installDependencies:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i
      - name: Hoist Bootstrap Lerna
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm run bootstrap:hoist
      - name: Bootstrap Lerna
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm run bootstrap
      - name: Build Modules
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm run build
      - name: Test Code
        uses: mujo-code/puppeteer-headful@8f2b2fb
        env:
          CI: 'true'
        with:
          args: npm test
