on: push
name: Test Workflow
jobs:
  installDependencies:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install yarn --global
      - name: Install Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - name: Yarn install
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn build
      - name: Test Code
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: yarn test
